version: "3.9"

services:
  database:
    container_name: orecart-database-staging
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - orecart-db-volume-staging:/var/lib/postgresql/data
    env_file:
      - database.env
    networks:
      - staging
  migration:
    container_name: orecart-migration-staging
    build: ./backend
    command: alembic upgrade head
    env_file:
      - backend.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - staging
  backend:
    container_name: orecart-backend-staging
    build: ./backend
    restart: always
    env_file:
      - backend.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - staging
  # frontend-admin:
  #   container_name: orecart-frontend-admin-staging
  #   build: ./frontend-admin
  #   restart: always
  #   ports:
  #     - 5173:5173
  #   env_file:
  #     - frontend-admin.env
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5173/"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 10s
  #   depends_on:
  #     backend:
  #       condition: service_healthy
networks:
  staging:

volumes:
  orecart-db-volume-staging: {}
