version: "3.9"

services:
  database:
    container_name: orecart-database
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 5432:5432
    volumes:
      - orecart-db-volume:/var/lib/postgresql/data
    env_file:
      - database.env
  migration:
    container_name: orecart-migration
    build: ./backend
    command: alembic upgrade head
    env_file:
      - backend.env
    depends_on:
      database:
        condition: service_healthy
  backend:
    container_name: orecart-backend
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - backend.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      migration:
        condition: service_completed_successfully
  frontend-admin:
    container_name: orecart-frontend-admin
    build: ./frontend-admin
    restart: always
    ports:
      - 5173:5173
    env_file:
      - frontend-admin.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy
volumes:
  orecart-db-volume: {}
