version: "3.9"

services:
  database:
    container_name: orecart-database
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - 5432:5432
    volumes:
      - orecart-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  backend:
    container_name: orecart-backend
    build: ./backend
    restart: always
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:password@database:5432/postgres
      - CACHE_TYPE=ttl
  frontend-admin:
    container_name: orecart-frontend-admin
    build: ./frontend-admin
    restart: always
    ports:
      - 5173:5173
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ADMIN_URL=http://localhost:3000
      - REACT_APP_ADMIN=true
volumes:
  orecart-db-volume: {}
