version : “3”
services :
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - orecode-app_prod
      - staging_staging

networks:
  orecode-app_prod:
    external: true
  staging_staging:
    external: true