version : “3”
services :
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - prod
      - staging

networks:
  prod:
    external: true
  staging:
    external: true