version: "3.9"

services:
  database:
    container_name: orecode-database
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - orecode-db-volume:/var/lib/postgresql/data
    env_file:
      - database.env
    networks:
      - prod
  migration:
    container_name: orecode-migration
    build: ./backend
    command: alembic upgrade head
    env_file:
      - backend.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - prod
  backend:
    container_name: orecode-backend
    build: ./backend
    restart: always
    env_file:
      - backend.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - prod
networks:
  prod:

volumes:
  orecode-db-volume: {}
