#!/bin/bash

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    echo "Please do not push to the main branch! Please make a branch push there and open a pull request to get code into the main branch."
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
