name: Lint-Node

on: [push, pull_request]
  branches: [main]

jobs:
  lint-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: clean install
        working-directory: ./frontend/
        run: npm ci
      - name: run eslint
        working-directory: ./frontend/
        run: |
          npx eslint App.tsx `find ./src -type f \( -name "*.ts" -o -name "*.tsx" \)` --debug
