name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.13"
          max-line-length: "120"
      - run: pip install black mypy isort
      - run: black --check --diff ./backend/
      - run: isort --check --diff ./backend/
      - run: mypy ./backend/

  
  