name: Lint-Python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.13"
      - run: pip install -r ./backend/requirements.txt
      - run: black --check --diff ./backend/
      - run: isort --profile black --check --diff ./backend/
      - run: mypy ./backend/
      - run: pylint --rcfile ./backend/pylintrc -E ./backend/
      - run: pytest ./backend/
